apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: dionysbiz
    provider: github
    repository: demo-php-helloworld
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: dionysbiz-demo-php-helloworld
  namespace: jx
spec:
  httpCloneURL: https://github.com/dionysbiz/demo-php-helloworld.git
  org: dionysbiz
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: demo-php-helloworld
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/dionysbiz/demo-php-helloworld
