# Source: chartmuseum/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-x-chartmuseum
  labels:
    helm.sh/chart: chartmuseum-3.9.1
    app.kubernetes.io/name: chartmuseum
    app.kubernetes.io/instance: chartmuseum
    app.kubernetes.io/version: "0.15.0"
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    secret.jenkins-x.io/schema-object: '{"name":"jenkins-x-chartmuseum","properties":[{"name":"BASIC_AUTH_USER","question":"chartmuseum repository user name","help":"The username used to authenticate with chartmuseum (the helm repository)","defaultValue":"admin"},{"name":"BASIC_AUTH_PASS","question":"chartmuseum repository password","help":"The password to authenticate with the chartmuseum (the helm repository)","generator":"password","minLength":5,"maxLength":41}],"mandatory":true}'
spec:
  backendType: gcpSecretsManager
  projectId: dionysbiz
  data:
  - name: BASIC_AUTH_PASS
    key: autopilot-cluster-jx-jx-admin-user
    property: password
    version: latest
  - name: BASIC_AUTH_USER
    key: autopilot-cluster-jx-jx-admin-user
    property: username
    version: latest
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'chartmuseum'
        secret.jenkins-x.io/schema-object: '{"name":"jenkins-x-chartmuseum","properties":[{"name":"BASIC_AUTH_USER","question":"chartmuseum repository user name","help":"The username used to authenticate with chartmuseum (the helm repository)","defaultValue":"admin"},{"name":"BASIC_AUTH_PASS","question":"chartmuseum repository password","help":"The password to authenticate with the chartmuseum (the helm repository)","generator":"password","minLength":5,"maxLength":41}],"mandatory":true}'
      labels:
        helm.sh/chart: chartmuseum-3.9.1
        app.kubernetes.io/name: chartmuseum
        app.kubernetes.io/instance: chartmuseum
        app.kubernetes.io/version: "0.15.0"
        app.kubernetes.io/managed-by: Helm
    type: Opaque
