# Source: chartmuseum/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-x-chartmuseum
  labels:
    app.kubernetes.io/name: chartmuseum
    app.kubernetes.io/instance: chartmuseum
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'chartmuseum'
  namespace: jx
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
